@apiurl = http://localhost:4000

post {{apiurl}}/parties
Content-Type: application/json

{
    "title":"hello test",
    "authorId":242342,
    "datetime":"2024-11-24T10:07:36.131Z"
}

###

GET {{apiurl}}/parties